In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Q.1
df=pd.read_csv("adultPrac7.csv")

In [ ]:
df.head()

age          workclass  fnlwgt   education  education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital_status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital_gain  capital_loss  hours_per_week  native_country  income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64 
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64 
 11  capital_loss    32561 non-null  int64 
 12  hours_per_week  32561 non-null  int64 
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


The categorical classes are workclass, education, marital_status, occupation, relationship, race, sex, native_country, income

In [ ]:
df.describe()

age        fnlwgt  education_num  capital_gain  capital_loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000   
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830   
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours_per_week  
count    32561.000000  
mean        40.437456  
std         12.347429  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

In [ ]:
df.size

488415

In [ ]:
df.head(20)

age          workclass  fnlwgt      education  education_num  \
0    39          State-gov   77516      Bachelors             13   
1    50   Self-emp-not-inc   83311      Bachelors             13   
2    38            Private  215646        HS-grad              9   
3    53            Private  234721           11th              7   
4    28            Private  338409      Bachelors             13   
5    37            Private  284582        Masters             14   
6    49            Private  160187            9th              5   
7    52   Self-emp-not-inc  209642        HS-grad              9   
8    31            Private   45781        Masters             14   
9    42            Private  159449      Bachelors             13   
10   37            Private  280464   Some-college             10   
11   30          State-gov  141297      Bachelors             13   
12   23            Private  122272      Bachelors             13   
13   32            Private  205019     Assoc-acdm             12   
14   40            Private  121772      Assoc-voc             11   
15   34            Private  245487        7th-8th              4   
16   25   Self-emp-not-inc  176756        HS-grad              9   
17   32            Private  186824        HS-grad              9   
18   38            Private   28887           11th              7   
19   43   Self-emp-not-inc  292175        Masters             14   

            marital_status          occupation    relationship  \
0            Never-married        Adm-clerical   Not-in-family   
1       Married-civ-spouse     Exec-managerial         Husband   
2                 Divorced   Handlers-cleaners   Not-in-family   
3       Married-civ-spouse   Handlers-cleaners         Husband   
4       Married-civ-spouse      Prof-specialty            Wife   
5       Married-civ-spouse     Exec-managerial            Wife   
6    Married-spouse-absent       Other-service   Not-in-family   
7       Married-civ-spouse     Exec-managerial         Husband   
8            Never-married      Prof-specialty   Not-in-family   
9       Married-civ-spouse     Exec-managerial         Husband   
10      Married-civ-spouse     Exec-managerial         Husband   
11      Married-civ-spouse      Prof-specialty         Husband   
12           Never-married        Adm-clerical       Own-child   
13           Never-married               Sales   Not-in-family   
14      Married-civ-spouse        Craft-repair         Husband   
15      Married-civ-spouse    Transport-moving         Husband   
16           Never-married     Farming-fishing       Own-child   
17           Never-married   Machine-op-inspct       Unmarried   
18      Married-civ-spouse               Sales         Husband   
19                Divorced     Exec-managerial       Unmarried   

                   race      sex  capital_gain  capital_loss  hours_per_week  \
0                 White     Male          2174             0              40   
1                 White     Male             0             0              13   
2                 White     Male             0             0              40   
3                 Black     Male             0             0              40   
4                 Black   Female             0             0              40   
5                 White   Female             0             0              40   
6                 Black   Female             0             0              16   
7                 White     Male             0             0              45   
8                 White   Female         14084             0              50   
9                 White     Male          5178             0              40   
10                Black     Male             0             0              80   
11   Asian-Pac-Islander     Male             0             0              40   
12                White   Female             0             0              30   
13                Black     Male             0             0        

In [ ]:
np.unique(df.isnull())

array([False])

There are null values in the dataset

In [ ]:
df["age"].unique()

array([39, 50, 38, 53, 28, 37, 49, 52, 31, 42, 30, 23, 32, 40, 34, 25, 43,
       54, 35, 59, 56, 19, 20, 45, 22, 48, 21, 24, 57, 44, 41, 29, 18, 47,
       46, 36, 79, 27, 67, 33, 76, 17, 55, 61, 70, 64, 71, 68, 66, 51, 58,
       26, 60, 90, 75, 65, 77, 62, 63, 80, 72, 74, 69, 73, 81, 78, 88, 82,
       83, 84, 85, 86, 87])

In [ ]:
df["workclass"].unique()

array([' State-gov', ' Self-emp-not-inc', ' Private', ' Federal-gov',
       ' Local-gov', ' ?', ' Self-emp-inc', ' Without-pay',
       ' Never-worked'], dtype=object)

In [ ]:
df["fnlwgt"].unique()

array([ 77516,  83311, 215646, ...,  34066,  84661, 257302])

In [ ]:
df["education"].unique()

array([' Bachelors', ' HS-grad', ' 11th', ' Masters', ' 9th',
       ' Some-college', ' Assoc-acdm', ' Assoc-voc', ' 7th-8th',
       ' Doctorate', ' Prof-school', ' 5th-6th', ' 10th', ' 1st-4th',
       ' Preschool', ' 12th'], dtype=object)

In [ ]:
df["education_num"].unique()

array([13,  9,  7, 14,  5, 10, 12, 11,  4, 16, 15,  3,  6,  2,  1,  8])

In [ ]:
df["marital_status"].unique()

array([' Never-married', ' Married-civ-spouse', ' Divorced',
       ' Married-spouse-absent', ' Separated', ' Married-AF-spouse',
       ' Widowed'], dtype=object)

In [ ]:
df["occupation"].unique()

array([' Adm-clerical', ' Exec-managerial', ' Handlers-cleaners',
       ' Prof-specialty', ' Other-service', ' Sales', ' Craft-repair',
       ' Transport-moving', ' Farming-fishing', ' Machine-op-inspct',
       ' Tech-support', ' ?', ' Protective-serv', ' Armed-Forces',
       ' Priv-house-serv'], dtype=object)

In [ ]:
df["native_country"].unique()

array([' United-States', ' Cuba', ' Jamaica', ' India', ' ?', ' Mexico',
       ' South', ' Puerto-Rico', ' Honduras', ' England', ' Canada',
       ' Germany', ' Iran', ' Philippines', ' Italy', ' Poland',
       ' Columbia', ' Cambodia', ' Thailand', ' Ecuador', ' Laos',
       ' Taiwan', ' Haiti', ' Portugal', ' Dominican-Republic',
       ' El-Salvador', ' France', ' Guatemala', ' China', ' Japan',
       ' Yugoslavia', ' Peru', ' Outlying-US(Guam-USVI-etc)', ' Scotland',
       ' Trinadad&Tobago', ' Greece', ' Nicaragua', ' Vietnam', ' Hong',
       ' Ireland', ' Hungary', ' Holand-Netherlands'], dtype=object)

The problem with occupation, workclass, native_country is that they have " ?" have this as a value in their column

In [ ]:
#df=pd.read_csv("adultPrac7.csv",na_values=[" ?","??","???","????"])
df=df.replace(" ?", "NaN")

In [ ]:
df=df.replace("nan","NaN")

In [ ]:
df["workclass"].unique()

array([' State-gov', ' Self-emp-not-inc', ' Private', ' Federal-gov',
       ' Local-gov', 'NaN', ' Self-emp-inc', ' Without-pay',
       ' Never-worked'], dtype=object)

In [ ]:
df["occupation"].unique()

array([' Adm-clerical', ' Exec-managerial', ' Handlers-cleaners',
       ' Prof-specialty', ' Other-service', ' Sales', ' Craft-repair',
       ' Transport-moving', ' Farming-fishing', ' Machine-op-inspct',
       ' Tech-support', 'NaN', ' Protective-serv', ' Armed-Forces',
       ' Priv-house-serv'], dtype=object)

In [ ]:
df["native_country"].unique()

array([' United-States', ' Cuba', ' Jamaica', ' India', 'NaN', ' Mexico',
       ' South', ' Puerto-Rico', ' Honduras', ' England', ' Canada',
       ' Germany', ' Iran', ' Philippines', ' Italy', ' Poland',
       ' Columbia', ' Cambodia', ' Thailand', ' Ecuador', ' Laos',
       ' Taiwan', ' Haiti', ' Portugal', ' Dominican-Republic',
       ' El-Salvador', ' France', ' Guatemala', ' China', ' Japan',
       ' Yugoslavia', ' Peru', ' Outlying-US(Guam-USVI-etc)', ' Scotland',
       ' Trinadad&Tobago', ' Greece', ' Nicaragua', ' Vietnam', ' Hong',
       ' Ireland', ' Hungary', ' Holand-Netherlands'], dtype=object)

In [ ]:
np.unique(df["age"].isnull()).sum()

0

In [ ]:
np.unique(df["fnlwgt"].isnull()).sum()

0

In [ ]:
np.unique(df["education_num"].isnull()).sum()

0

In [ ]:
np.unique(df["capital_gain"].isnull()).sum()

0

In [ ]:
np.unique(df["capital_loss"].isnull()).sum()

0

In [ ]:
np.unique(df["hours_per_week"].isnull()).sum()

0

There are no Null Values

In [ ]:
X=df[["age", 'workclass', 'fnlwgt',	'education','marital_status',	'occupation',	'relationship',
      'race',	'sex',	'capital_gain',	'capital_loss',
      'hours_per_week', 'native_country']]
X.head()

age          workclass  fnlwgt   education       marital_status  \
0   39          State-gov   77516   Bachelors        Never-married   
1   50   Self-emp-not-inc   83311   Bachelors   Married-civ-spouse   
2   38            Private  215646     HS-grad             Divorced   
3   53            Private  234721        11th   Married-civ-spouse   
4   28            Private  338409   Bachelors   Married-civ-spouse   

           occupation    relationship    race      sex  capital_gain  \
0        Adm-clerical   Not-in-family   White     Male          2174   
1     Exec-managerial         Husband   White     Male             0   
2   Handlers-cleaners   Not-in-family   White     Male             0   
3   Handlers-cleaners         Husband   Black     Male             0   
4      Prof-specialty            Wife   Black   Female             0   

   capital_loss  hours_per_week  native_country  
0             0              40   United-States  
1             0              13   United-States  
2             0              40   United-States  
3             0              40   United-States  
4             0              40            Cuba

In [ ]:
Y=df[["income"]]
Y.head()

income
0   <=50K
1   <=50K
2   <=50K
3   <=50K
4   <=50K

In [ ]:
def label_encoding(column_name, data_frame):
  a=np.unique(data_frame[column_name])
  b=list(np.arange(0,len(a)))
  print(a,b)
  for i in b:
    data_frame[column_name]=data_frame[column_name].replace(a[i],b[i])

  return data_frame

a=input("Enter the name of the feature in which you want to do label-encoding: ")
Y=label_encoding(a,Y)
Y.head()

Enter the name of the feature in which you want to do label-encoding: income
[' <=50K' ' >50K'] [0, 1]


<ipython-input-33-ac0db8941f37>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_frame[column_name]=data_frame[column_name].replace(a[i],b[i])


income
0       0
1       0
2       0
3       0
4       0

In [ ]:
def label_encoding(column_name, data_frame):
  a=np.unique(data_frame[column_name])
  b=list(np.arange(0,len(a)))
  print(a,b)
  for i in b:
    data_frame[column_name]=data_frame[column_name].replace(a[i],b[i])

  return data_frame

i=int(input("Enter the number of categorical classes: "))
for j in range(i):
  a=input("Enter the name of the feature in which you want to do label-encoding: ")
  df1=label_encoding(a,X)
  print()
  df1.head()



Enter the number of categorical classes: 8
Enter the name of the feature in which you want to do label-encoding: workclass
[' Federal-gov' ' Local-gov' ' Never-worked' ' Private' ' Self-emp-inc'
 ' Self-emp-not-inc' ' State-gov' ' Without-pay' 'NaN'] [0, 1, 2, 3, 4, 5, 6, 7, 8]


<ipython-input-34-b0faa4ee7457>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_frame[column_name]=data_frame[column_name].replace(a[i],b[i])



Enter the name of the feature in which you want to do label-encoding: education
[' 10th' ' 11th' ' 12th' ' 1st-4th' ' 5th-6th' ' 7th-8th' ' 9th'
 ' Assoc-acdm' ' Assoc-voc' ' Bachelors' ' Doctorate' ' HS-grad'
 ' Masters' ' Preschool' ' Prof-school' ' Some-college'] [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

Enter the name of the feature in which you want to do label-encoding: race
[' Amer-Indian-Eskimo' ' Asian-Pac-Islander' ' Black' ' Other' ' White'] [0, 1, 2, 3, 4]

Enter the name of the feature in which you want to do label-encoding: sex
[' Female' ' Male'] [0, 1]

Enter the name of the feature in which you want to do label-encoding: native_country
[' Cambodia' ' Canada' ' China' ' Columbia' ' Cuba' ' Dominican-Republic'
 ' Ecuador' ' El-Salvador' ' England' ' France' ' Germany' ' Greece'
 ' Guatemala' ' Haiti' ' Holand-Netherlands' ' Honduras' ' Hong'
 ' Hungary' ' India' ' Iran' ' Ireland' ' Italy' ' Jamaica' ' Japan'
 ' Laos' ' Mexico' ' Nicaragua' ' Outlying-US(G

In [ ]:
df1.head()

age  workclass  fnlwgt  education  marital_status  occupation  \
0   39          6   77516          9               4           0   
1   50          5   83311          9               2           3   
2   38          3  215646         11               0           5   
3   53          3  234721          1               2           5   
4   28          3  338409          9               2           9   

   relationship  race  sex  capital_gain  capital_loss  hours_per_week  \
0             1     4    1          2174             0              40   
1             0     4    1             0             0              13   
2             1     4    1             0             0              40   
3             0     2    1             0             0              40   
4             5     2    0             0             0              40   

   native_country  
0              38  
1              38  
2              38  
3              38  
4               4

In [ ]:
v=["age", 'workclass', 'fnlwgt',	'education','marital_status',	'occupation',	'relationship',
      'race',	'sex',	'capital_gain',	'capital_loss',
      'hours_per_week', 'native_country']
for i in v:
  a=max(X[i])
  b=min(X[i])
  X[i]=((X[i]-b)/(a-b))

X.head()

X.head()


<ipython-input-36-48756aa704c2>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[i]=((X[i]-b)/(a-b))


age  workclass    fnlwgt  education  marital_status  occupation  \
0  0.301370      0.750  0.044302   0.600000        0.666667    0.000000   
1  0.452055      0.625  0.048238   0.600000        0.333333    0.214286   
2  0.287671      0.375  0.138113   0.733333        0.000000    0.357143   
3  0.493151      0.375  0.151068   0.066667        0.333333    0.357143   
4  0.150685      0.375  0.221488   0.600000        0.333333    0.642857   

   relationship  race  sex  capital_gain  capital_loss  hours_per_week  \
0           0.2   1.0  1.0       0.02174           0.0        0.397959   
1           0.0   1.0  1.0       0.00000           0.0        0.122449   
2           0.2   1.0  1.0       0.00000           0.0        0.397959   
3           0.0   0.5  1.0       0.00000           0.0        0.397959   
4           1.0   0.5  0.0       0.00000           0.0        0.397959   

   native_country  
0        0.926829  
1        0.926829  
2        0.926829  
3        0.926829  
4        0.097561

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
neigh=KNeighborsClassifier(n_neighbors=5)
neigh.fit(X, Y)
print(neigh.predict([[0.49,0.37,0.149,0.08,0.28,0.3,0,0.5,1,0.0001,0,0.4,0.92]]))

[0]


/usr/local/lib/python3.9/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)
print(y_pred)
np.unique(y_pred)

[0 0 0 ... 1 1 0]


/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 1])

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[4700,  218],
       [1104,  491]])

In [ ]:
from sklearn.metrics import classification_report
target_names = ['Below 50k', 'above 50K']
print(classification_report(y_test, y_pred, target_names=target_names))

              precision    recall  f1-score   support

   Below 50k       0.81      0.96      0.88      4918
   above 50K       0.69      0.31      0.43      1595

    accuracy                           0.80      6513
   macro avg       0.75      0.63      0.65      6513
weighted avg       0.78      0.80      0.77      6513



In [ ]:
from sklearn import metrics
scores = np.array([0.1, 0.04, 0.35, 0.3])
fpr, tpr, thresholds = metrics.roc_curve(Y[:4], scores, pos_label=2)

/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_ranking.py:1029: UndefinedMetricWarning: No positive samples in y_true, true positive value should be meaningless
  warnings.warn(
